# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zedboard.xdc

# Block Designs: bd/zed_firewall/zed_firewall.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zed_firewall || ORIG_REF_NAME==zed_firewall} -quiet] -quiet

# IP: bd/zed_firewall/ip/zed_firewall_processing_system7_0_0/zed_firewall_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zed_firewall_processing_system7_0_0 || ORIG_REF_NAME==zed_firewall_processing_system7_0_0} -quiet] -quiet

# IP: bd/zed_firewall/ip/zed_firewall_hardware_firewall_0_0/zed_firewall_hardware_firewall_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zed_firewall_hardware_firewall_0_0 || ORIG_REF_NAME==zed_firewall_hardware_firewall_0_0} -quiet] -quiet

# IP: bd/zed_firewall/ip/zed_firewall_auto_pc_0/zed_firewall_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zed_firewall_auto_pc_0 || ORIG_REF_NAME==zed_firewall_auto_pc_0} -quiet] -quiet

# IP: bd/zed_firewall/ip/zed_firewall_ps7_0_axi_periph_0/zed_firewall_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zed_firewall_ps7_0_axi_periph_0 || ORIG_REF_NAME==zed_firewall_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zed_firewall/ip/zed_firewall_rst_ps7_0_50M_0/zed_firewall_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zed_firewall_rst_ps7_0_50M_0 || ORIG_REF_NAME==zed_firewall_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: /home/mohit/Desktop/bheeshm_project/bheeshm_project.gen/sources_1/bd/zed_firewall/zed_firewall_ooc.xdc
