# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mohit/Desktop/bheeshm_project/bheeshm_project.srcs/sources_1/bd/zed_firewall/ip/zed_firewall_processing_system7_0_0/zed_firewall_processing_system7_0_0.xci
# IP: The module: 'zed_firewall_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mohit/Desktop/bheeshm_project/bheeshm_project.gen/sources_1/bd/zed_firewall/ip/zed_firewall_processing_system7_0_0/zed_firewall_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_firewall_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/mohit/Desktop/bheeshm_project/bheeshm_project.srcs/sources_1/bd/zed_firewall/ip/zed_firewall_processing_system7_0_0/zed_firewall_processing_system7_0_0.xci
# IP: The module: 'zed_firewall_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mohit/Desktop/bheeshm_project/bheeshm_project.gen/sources_1/bd/zed_firewall/ip/zed_firewall_processing_system7_0_0/zed_firewall_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_firewall_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
